/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalaki.CombatResult;
import napakalaki.Monster;
import napakalaki.Napakalaki;
import napakalaki.Player;

/**
 *
 * @author Jonathan
 */
public class NapakalakiView extends javax.swing.JFrame {

    Napakalaki napakalakiModel;
    Player currentPlayer;
    Monster currentMonster;
    int ronda = 0;
    
    
    public void setNapakalaki(Napakalaki n){
        napakalakiModel = n;
        currentPlayer = n.getCurrentPlayer();
        currentMonster = n.getCurrentMonster();
        if(ronda < 3){
            currentPlayer.initTreasures();
            ronda++;
        }
        this.playerView1.setPlayer(currentPlayer);
        this.playerView1.setNapakalaki(napakalakiModel);
        this.playerView1.activarHacerVisible();
        this.playerView1.desactivarDiscard();
        this.playerView1.desactivarSteal();
        this.combatResultText.setText("");
        this.combatButton.setEnabled(false);
        this.nextTurnButton.setEnabled(false);
        this.showMonsterButton.setEnabled(true);
        this.monsterView1.setVisible(false);
        this.nextTurnButton.setVisible(false);
        this.turnoPasado.setVisible(false);
        this.vs.setVisible(false);
        this.turnoPasado.setText("");
        this.exitButton.setVisible(false);
    }
    
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showMonsterButton = new javax.swing.JButton();
        nextTurnButton = new javax.swing.JButton();
        combatButton = new javax.swing.JButton();
        combatResultText = new javax.swing.JTextField();
        monsterView1 = new GUI.MonsterView();
        vs = new javax.swing.JLabel();
        turnoPasado = new javax.swing.JTextField();
        playerView1 = new GUI.PlayerView();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        showMonsterButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        showMonsterButton.setText("MOSTRAR MONSTRUO");
        showMonsterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMonsterButtonActionPerformed(evt);
            }
        });

        nextTurnButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nextTurnButton.setText("PASAR TURNO");
        nextTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnButtonActionPerformed(evt);
            }
        });

        combatButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        combatButton.setText("COMBATIR");
        combatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatButtonActionPerformed(evt);
            }
        });

        combatResultText.setEditable(false);

        vs.setFont(new java.awt.Font("Trajan Pro", 0, 36)); // NOI18N
        vs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_81709.png"))); // NOI18N

        turnoPasado.setEditable(false);

        exitButton.setText("SALIR");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vs)
                        .addGap(179, 179, 179)
                        .addComponent(combatResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combatButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showMonsterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turnoPasado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextTurnButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vs, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combatResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitButton))
                        .addGap(35, 35, 35)
                        .addComponent(showMonsterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(combatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(turnoPasado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextTurnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatButtonActionPerformed
        CombatResult combatResult;
        combatResult = napakalakiModel.developCombat();
        System.out.println(combatResult);
          switch (combatResult) {
            case WINGAME : 
              this.combatResultText.setText("¡Has ganado la partida!");
              this.playerView1.setPlayer(currentPlayer);
              this.exitButton.setVisible(true);
              this.nextTurnButton.setVisible(false);
              this.showMonsterButton.setEnabled(false);
              this.combatButton.setEnabled(false);
              this.playerView1.desactivarDiscard();
              this.playerView1.desactivarHacerVisible();
              this.playerView1.desactivarSteal();
              break;
            case WIN :
              this.combatResultText.setText("¡Has ganado el combate!");
              this.playerView1.setPlayer(currentPlayer);
              break;
            case LOSE :
              this.combatResultText.setText("¡Has perdido el combate!");
              this.playerView1.setPlayer(currentPlayer);
              break;
            case LOSEANDCONVERT :
              this.combatResultText.setText("¡Has perdido el combate y te conviertes en sectario!");
              currentPlayer = napakalakiModel.getCurrentPlayer();
              this.playerView1.setPlayer(currentPlayer);
              break;
          }
        boolean valid = currentPlayer.validState();        
        if(valid){
            this.playerView1.activarHacerVisible();
            this.playerView1.desactivarDiscard();
            this.playerView1.activarSteal();
            repaint();
        }else{
            this.playerView1.setPlayer(currentPlayer);
            this.playerView1.monstrarCondiciones();
            this.playerView1.desactivarHacerVisible();
            this.playerView1.activarDiscard();
            this.playerView1.desactivarSteal();
            repaint();
        }
        this.nextTurnButton.setEnabled(true);

        this.showMonsterButton.setEnabled(false);
        this.combatButton.setEnabled(false);
        repaint();
    }//GEN-LAST:event_combatButtonActionPerformed

    private void nextTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnButtonActionPerformed
        boolean allowed = napakalakiModel.nextTurn();
        if(allowed){
            setNapakalaki(napakalakiModel);
            this.playerView1.activarHacerVisible();
            this.playerView1.desactivarDiscard();
            this.playerView1.desactivarSteal();
            this.showMonsterButton.setEnabled(true);
            repaint();
        }else{
            this.playerView1.setPlayer(currentPlayer);
            this.playerView1.monstrarCondiciones();
            this.playerView1.desactivarHacerVisible();
            this.playerView1.activarDiscard();
            this.playerView1.desactivarSteal();
            this.turnoPasado.setVisible(true);
            this.turnoPasado.setText("No es posible pasar el turno");
            repaint();
        }
    }//GEN-LAST:event_nextTurnButtonActionPerformed

    private void showMonsterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMonsterButtonActionPerformed
        this.monsterView1.setMonster(currentMonster);
        this.monsterView1.setVisible(true);
        this.combatButton.setEnabled(true);
        this.nextTurnButton.setEnabled(false);
        this.nextTurnButton.setVisible(true);
        this.vs.setVisible(true);
        this.playerView1.desactivarHacerVisible();
        this.playerView1.desactivarDiscard();
        this.playerView1.desactivarSteal();
        this.showMonsterButton.setEnabled(false);
        repaint();
    }//GEN-LAST:event_showMonsterButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showView() {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combatButton;
    private javax.swing.JTextField combatResultText;
    private javax.swing.JButton exitButton;
    private GUI.MonsterView monsterView1;
    private javax.swing.JButton nextTurnButton;
    private GUI.PlayerView playerView1;
    private javax.swing.JButton showMonsterButton;
    private javax.swing.JTextField turnoPasado;
    private javax.swing.JLabel vs;
    // End of variables declaration//GEN-END:variables
}
