/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JPanel;
import napakalaki.Napakalaki;
import napakalaki.Player;
import napakalaki.Treasure;

/**
 *
 * @author Jonathan
 */
public class PlayerView extends javax.swing.JPanel {

    public Player playerModel;
    private static Napakalaki napakalakiModel;
    
    public void setPlayer(Player p){
        playerModel = p;
        this.name.setText(playerModel.getName());
        this.level.setText(Integer.toString(playerModel.getLevels()));
        if(playerModel.soySectario()){
            this.sectario.setText("El jugador es sectario");
        }else{
            this.sectario.setText("");
        }
        this.pendingBadConsequence1.setPendingBadConsequence(playerModel.getPendingBadConsequence());
        this.pendingBadConsequence1.setVisible(false);
        fillTreasurePanel(PanelVisibleTreasures, playerModel.getVisibleTreasures());
        fillTreasurePanel(PanelHiddenTreasures, playerModel.getHiddenTreasures());
        this.enemigoName.setText(playerModel.getEnemy().getName());
        repaint();


    }
    
    public void monstrarCondiciones(){
        this.pendingBadConsequence1.setVisible(true);
    }
    public void activarHacerVisible(){
        MakeVisibleButton.setEnabled(true);
    }
    public void desactivarHacerVisible(){
        MakeVisibleButton.setEnabled(false);
    }
    public void activarDiscard(){
        DiscardButton.setEnabled(true);
        DiscardAllButton.setEnabled(true);
    }
    public void desactivarDiscard(){
        DiscardButton.setEnabled(false);
        DiscardAllButton.setEnabled(false);
    }
    public void activarSteal(){
        StealTreasureButton.setEnabled(true);
    }
    public void desactivarSteal(){
        StealTreasureButton.setEnabled(false);
    }
    
    public void setNapakalaki(Napakalaki n){
        napakalakiModel = n;
    }
    
    private ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) {
        TreasureView tv;
        ArrayList<Treasure> output = new ArrayList();
        for (Component c : aPanel.getComponents()) {
            tv = (TreasureView) c;
            if ( tv.isSelected() )
                output.add ( tv.getTreasure() );
        }
        return output;
    }
    
    private void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) {
        aPanel.removeAll();
        // Se recorre la lista de tesoros construyendo y añadiendo sus vistas
        // al panel
        for (Treasure t : aList) {
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure (t);
            aTreasureView.setVisible (true);
            aPanel.add (aTreasureView);
        }
        // Se fuerza la actualización visual del panel
        aPanel.repaint();
        aPanel.revalidate();
    }
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        NameTitle = new javax.swing.JLabel();
        LevelTitle = new javax.swing.JLabel();
        PanelVisibleTreasures = new javax.swing.JPanel();
        PanelHiddenTreasures = new javax.swing.JPanel();
        StealTreasureButton = new javax.swing.JToggleButton();
        MakeVisibleButton = new javax.swing.JToggleButton();
        DiscardButton = new javax.swing.JToggleButton();
        DiscardAllButton = new javax.swing.JToggleButton();
        name = new javax.swing.JTextField();
        level = new javax.swing.JTextField();
        sectario = new javax.swing.JTextField();
        TreasuresHiddenTitle = new javax.swing.JLabel();
        TreasuresVisibleTitle = new javax.swing.JLabel();
        pendingBadConsequence1 = new GUI.PendingBadConsequence();
        Enemigo = new javax.swing.JLabel();
        enemigoName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(247, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 2));

        Title.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        Title.setText("Jugador");

        NameTitle.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        NameTitle.setText("Nombre:");

        LevelTitle.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        LevelTitle.setText("Nivel:");

        PanelVisibleTreasures.setBackground(new java.awt.Color(255, 255, 255));
        PanelVisibleTreasures.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 0)));
        PanelVisibleTreasures.setForeground(new java.awt.Color(0, 153, 0));
        PanelVisibleTreasures.setPreferredSize(new java.awt.Dimension(170, 280));

        PanelHiddenTreasures.setBackground(new java.awt.Color(255, 255, 255));
        PanelHiddenTreasures.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 0)));
        PanelHiddenTreasures.setForeground(new java.awt.Color(204, 0, 0));
        PanelHiddenTreasures.setPreferredSize(new java.awt.Dimension(100, 280));

        StealTreasureButton.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        StealTreasureButton.setText("Robar Tesoro");
        StealTreasureButton.setPreferredSize(new java.awt.Dimension(105, 30));
        StealTreasureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StealTreasureButtonActionPerformed(evt);
            }
        });

        MakeVisibleButton.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        MakeVisibleButton.setText("Hacer Visible");
        MakeVisibleButton.setPreferredSize(new java.awt.Dimension(105, 30));
        MakeVisibleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeVisibleButtonActionPerformed(evt);
            }
        });

        DiscardButton.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        DiscardButton.setText("Descartar");
        DiscardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscardButtonActionPerformed(evt);
            }
        });

        DiscardAllButton.setFont(new java.awt.Font("Trajan Pro", 0, 10)); // NOI18N
        DiscardAllButton.setText("Descartar Todo");
        DiscardAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscardAllButtonActionPerformed(evt);
            }
        });

        name.setEditable(false);
        name.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        level.setEditable(false);
        level.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N

        sectario.setEditable(false);

        TreasuresHiddenTitle.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        TreasuresHiddenTitle.setText("Tesoros ocultos");

        TreasuresVisibleTitle.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        TreasuresVisibleTitle.setText("Tesoros Visibles");

        Enemigo.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        Enemigo.setText("Enemigo:");

        enemigoName.setEditable(false);
        enemigoName.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Title)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NameTitle))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LevelTitle)
                                            .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(sectario, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MakeVisibleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(StealTreasureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DiscardAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DiscardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enemigoName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Enemigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(PanelHiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelVisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TreasuresHiddenTitle)
                        .addGap(157, 157, 157)
                        .addComponent(TreasuresVisibleTitle)
                        .addGap(87, 87, 87))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pendingBadConsequence1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Title)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameTitle)
                            .addComponent(LevelTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(sectario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MakeVisibleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StealTreasureButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiscardAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiscardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Enemigo)
                        .addGap(18, 18, 18)
                        .addComponent(enemigoName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TreasuresHiddenTitle)
                            .addComponent(TreasuresVisibleTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelHiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                            .addComponent(PanelVisibleTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(pendingBadConsequence1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MakeVisibleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeVisibleButtonActionPerformed
        ArrayList<Treasure> selHidden = getSelectedTreasures (PanelHiddenTreasures);
        if(selHidden.size() != 0){
            napakalakiModel.makeTreasuresVisible (selHidden);
            setPlayer (napakalakiModel.getCurrentPlayer());
        }
        repaint();
        MakeVisibleButton.setSelected(false);
    }//GEN-LAST:event_MakeVisibleButtonActionPerformed

    private void StealTreasureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StealTreasureButtonActionPerformed
        Treasure t;
        t = playerModel.stealTreasure();
        setPlayer (napakalakiModel.getCurrentPlayer());
        repaint();
        StealTreasureButton.setSelected(false);
    }//GEN-LAST:event_StealTreasureButtonActionPerformed

    private void DiscardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscardButtonActionPerformed
        ArrayList<Treasure> selHidden = getSelectedTreasures (PanelHiddenTreasures);
        if(selHidden.size() != 0){
            napakalakiModel.discardHiddenTreasures(selHidden);
            for(int i=0; i<selHidden.size(); ++i) {
                napakalakiModel.getCurrentPlayer().getPendingBadConsequence().substractHiddenTreasure(selHidden.get(i));
            }
            setPlayer (napakalakiModel.getCurrentPlayer());
            
        }
        ArrayList<Treasure> selVisible = getSelectedTreasures (PanelVisibleTreasures);
        if(selVisible.size() != 0){
            napakalakiModel.discardVisibleTreasures(selVisible);
            for(int i=0; i<selVisible.size(); ++i) {
                napakalakiModel.getCurrentPlayer().getPendingBadConsequence().substractVisibleTreasure(selVisible.get(i));
            }
            setPlayer (napakalakiModel.getCurrentPlayer());

        }
        repaint();
        DiscardButton.setSelected(false);
    }//GEN-LAST:event_DiscardButtonActionPerformed

    private void DiscardAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscardAllButtonActionPerformed
        napakalakiModel.getCurrentPlayer().discardAllTreasures();
        setPlayer (napakalakiModel.getCurrentPlayer());
        repaint();
        DiscardAllButton.setSelected(false);
    }//GEN-LAST:event_DiscardAllButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton DiscardAllButton;
    private javax.swing.JToggleButton DiscardButton;
    private javax.swing.JLabel Enemigo;
    private javax.swing.JLabel LevelTitle;
    private javax.swing.JToggleButton MakeVisibleButton;
    private javax.swing.JLabel NameTitle;
    private javax.swing.JPanel PanelHiddenTreasures;
    private javax.swing.JPanel PanelVisibleTreasures;
    private javax.swing.JToggleButton StealTreasureButton;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TreasuresHiddenTitle;
    private javax.swing.JLabel TreasuresVisibleTitle;
    private javax.swing.JTextField enemigoName;
    private javax.swing.JTextField level;
    private javax.swing.JTextField name;
    private GUI.PendingBadConsequence pendingBadConsequence1;
    private javax.swing.JTextField sectario;
    // End of variables declaration//GEN-END:variables
}
